spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to EazyBank accounts related production APIs "
  contactDetails:
    name: "Reine Aishwarya - Product Owner"
    email: "{cipher}925e6cb275b5b25e14673ec900b7c5088cdb642721cbd422e2f35031b605dda2a0a733c5b9350c067b703e780af70149"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384
