build:
  version: "2.0"

cards:
  message: "Welcome to EazyBank accounts related CARDS QA APIs "
  contactDetails:
    name: "Nick - QA Lead"
    email: "nick@gmail.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371