
build:
  version: "1.0"

cards:
  message: "Welcome to EazyBank accounts related CARDS prod APIs "
  contactDetails:
    name: "Akash - Product Owner"
    email: "Akash@gmail.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384
